### ISSUE TITLE
Example http_server2.py doesn't work like described

### ISSUE THREAD

**Issue by mistrey** [thespianpy/Thespian#62]
With `python examples/httpserver/http_server2.py 8000` I end up with 
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/strey/Projekte/Thespian/thespian/system/multiprocCommon.py", line 631, in startChild
    lowestLevel = get_min_log_level(logDefs)
  File "/home/strey/Projekte/Thespian/thespian/system/multiprocCommon.py", line 568, in get_min_log_level
    root_data = logDefs.get('root')
AttributeError: 'NoneType' object has no attribute 'get'
```
`curl http://localhost:8000/` results in `curl: (7) Failed to connect to localhost port 8000: Verbindungsaufbau abgelehnt`.

**Comment by kquick** [comment]
Fixed in release 3.10.4
