### ISSUE TITLE
Spurious connection detection breaks multiprocTCPBase on MacOS 

### ISSUE THREAD

**Issue by gbanasiak** [thespianpy/Thespian#77]
This is a follow-up to https://github.com/thespianpy/Thespian/issues/70.

While investigating this issue it was suspected connections unrelated to Thespian might be interfering, see https://github.com/thespianpy/Thespian/issues/70#issuecomment-1381943558. This resulted in https://github.com/thespianpy/Thespian/commit/5a548597cf53cf17faff78ca49ba4d3939b217fb. Unfortunately this blocks legitimate connections on MacOS due to unexpected protocol mismatch, MacOS returns`lsock.proto == socket.IPPROTO_IP` (0) instead of `lsock.proto == socket.IPPROTO_TCP` (6).

This can be demonstrated with an extra log:
```
diff --git a/thespian/system/transport/TCPTransport.py b/thespian/system/transport/TCPTransport.py
index d8da06b..bb60b85 100644
--- a/thespian/system/transport/TCPTransport.py
+++ b/thespian/system/transport/TCPTransport.py
@@ -1354,6 +1354,7 @@ class TCPTransport(asyncTransportBase, wakeupTransportBase):
                 or lsock.family != socket.AF_INET
                 or lsock.type != socket.SOCK_STREAM):
                 # Spurious connection attempt: ignore
+                thesplog('Spurious connection: %s', lsock)
                 lsock.close()
                 return
             accepted = True
```

In [rally](https://github.com/elastic/rally) after `thespian.actors.ActorSystem("multiprocTCPBase", ...)` I'm getting the following in Thespian log:
```
2024-12-13 12:04:53.555268 p294 dbg  ++++ Starting Admin from /Users/grzegorz/src/rally/.venv/lib/python3.12/site-packages/thespian/__init__.py
2024-12-13 12:04:53.555781 p294 I    ++++ Admin started @ ActorAddr-(T|:1900) / gen (3, 10)
2024-12-13 12:04:53.559963 p294 I    Spurious connection: <socket.socket fd=12, family=2, type=1, proto=0, laddr=('192.168.1.61', 1900), raddr=('192.168.1.61', 56154)>
2024-12-13 12:04:53.596758 p294 I    Spurious connection: <socket.socket fd=12, family=2, type=1, proto=0, laddr=('192.168.1.61', 1900), raddr=('192.168.1.61', 56155)>
2024-12-13 12:04:53.657289 p294 I    Spurious connection: <socket.socket fd=12, family=2, type=1, proto=0, laddr=('192.168.1.61', 1900), raddr=('192.168.1.61', 56156)>
2024-12-13 12:04:53.758412 p294 I    Spurious connection: <socket.socket fd=12, family=2, type=1, proto=0, laddr=('192.168.1.61', 1900), raddr=('192.168.1.61', 56157)>
2024-12-13 12:04:53.928640 p294 I    Spurious connection: <socket.socket fd=12, family=2, type=1, proto=0, laddr=('192.168.1.61', 1900), raddr=('192.168.1.61', 56158)>
2024-12-13 12:04:54.215195 p294 I    Spurious connection: <socket.socket fd=12, family=2, type=1, proto=0, laddr=('192.168.1.61', 1900), raddr=('192.168.1.61', 56159)>
2024-12-13 12:04:54.701098 p294 I    Spurious connection: <socket.socket fd=12, family=2, type=1, proto=0, laddr=('192.168.1.61', 1900), raddr=('192.168.1.61', 56160)>
2024-12-13 12:04:55.526159 p294 I    Spurious connection: <socket.socket fd=12, family=2, type=1, proto=0, laddr=('192.168.1.61', 1900), raddr=('192.168.1.61', 56161)>
2024-12-13 12:04:56.926626 p294 I    Spurious connection: <socket.socket fd=12, family=2, type=1, proto=0, laddr=('192.168.1.61', 1900), raddr=('192.168.1.61', 56162)>
2024-12-13 12:04:58.570660 p294 I    Spurious connection: <socket.socket fd=12, family=2, type=1, proto=0, laddr=('127.0.0.1', 1900), raddr=('127.0.0.1', 56164)>
[..]
```

And the following stack trace in Rally log:

```
2024-12-13 11:04:53,532 -not-actor-/PID:278 esrally.rally INFO Actor system already running locally? [False]
2024-12-13 11:04:53,532 -not-actor-/PID:278 esrally.actor INFO Starting actor system with system base [multiprocTCPBase] and capabilities [{'coordinator': True, 'ip': '127.0.0.1', 'Convention Address.IPv4': '127.0.0.1:1900'}].
2024-12-13 11:04:53,556 -not-actor-/PID:294 root INFO ++++ Actor System gen (3, 10) started, admin @ ActorAddr-(T|:1900)
2024-12-13 11:04:53,556 -not-actor-/PID:294 root DEBUG Thespian source: /Users/grzegorz/src/rally/.venv/lib/python3.12/site-packages/thespian/__init__.py
2024-12-13 11:04:58,557 -not-actor-/PID:278 esrally.actor ERROR Could not initialize internal actor system.
Traceback (most recent call last):
  File "/Users/grzegorz/src/rally/esrally/actor.py", line 263, in bootstrap_actor_system
    return thespian.actors.ActorSystem(system_base, logDefs=log.load_configuration(), capabilities=capabilities)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grzegorz/src/rally/.venv/lib/python3.12/site-packages/thespian/actors.py", line 637, in __init__
    systemBase = self._startupActorSys(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grzegorz/src/rally/.venv/lib/python3.12/site-packages/thespian/actors.py", line 678, in _startupActorSys
    systemBase = sbc(self, logDefs=logDefs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grzegorz/src/rally/.venv/lib/python3.12/site-packages/thespian/system/multiprocTCPBase.py", line 28, in __init__
    super(ActorSystemBase, self).__init__(system, logDefs)
  File "/Users/grzegorz/src/rally/.venv/lib/python3.12/site-packages/thespian/system/multiprocCommon.py", line 83, in __init__
    super(multiprocessCommon, self).__init__(system, logDefs)
  File "/Users/grzegorz/src/rally/.venv/lib/python3.12/site-packages/thespian/system/systemBase.py", line 326, in __init__
    self._startAdmin(self.adminAddr,
  File "/Users/grzegorz/src/rally/.venv/lib/python3.12/site-packages/thespian/system/multiprocCommon.py", line 115, in _startAdmin
    raise InvalidActorAddress(adminAddr,
thespian.actors.InvalidActorAddress: ActorAddr-(T|:1900) is not a valid ActorSystem admin
```

Protocol reported is `proto=0` but these are definitely TCP connections:
<img width="1606" alt="Screenshot 2024-12-13 at 12 34 09" src="https://github.com/user-attachments/assets/fbd711f4-e3d7-4b05-a8ae-9ae7fd5fe9a6" />

Now the original issue reported in https://github.com/thespianpy/Thespian/issues/70, i.e. exception when running `lsock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)` makes more sense I guess. When socket is not considered TCP by the system, setting a TCP option fails.

The simplest fix would be to revert https://github.com/thespianpy/Thespian/commit/5a548597cf53cf17faff78ca49ba4d3939b217fb or add an extra condition:
```
diff --git a/thespian/system/transport/TCPTransport.py b/thespian/system/transport/TCPTransport.py
index bb60b85..bbff82e 100644
--- a/thespian/system/transport/TCPTransport.py
+++ b/thespian/system/transport/TCPTransport.py
@@ -1350,7 +1350,7 @@ class TCPTransport(asyncTransportBase, wakeupTransportBase):
         accepted = False
         try:
             lsock, rmtTxAddr = self.new_socket(self.socket.accept)
-            if (lsock.proto != socket.IPPROTO_TCP
+            if ((lsock.proto != socket.IPPROTO_TCP and lsock.proto != socket.IPPROTO_IP)
                 or lsock.family != socket.AF_INET
                 or lsock.type != socket.SOCK_STREAM):
                 # Spurious connection attempt: ignore
```

I can confirm this unblocks Rally use in MacOS after 3.10.7 while still addressing https://github.com/thespianpy/Thespian/issues/70, i.e. https://github.com/elastic/rally/issues/1575.

I can raise a PR if that's an acceptable approach?

I've tested using Sonoma 14.7.1.

**Comment by gbanasiak** [comment]
Additional clarification to Thespian log provided earlier. All the connectivity happens over loopback interface. The `192.168.1.61` address is my local address from some other interface than `lo0`.

**Comment by kquick** [comment]
Thank you for the report and investigation into this.  This doesn't sound like a great situation, but unfortunately I don't have access to a Mac at the moment to do any additional experimentation on so I am happy to defer to your direct experiences and would appreciate a PR that improves this situation for Macs.

**Comment by gbanasiak** [comment]
Many thanks for a quick response. I think revert makes the most sense. Connection filtering was introduced with the assumption `proto=0` was unrelated to Thespian, but it's not the case. I've raised https://github.com/thespianpy/Thespian/pull/79.

I've tested this with both MacOS Sonoma 14.7.1/14.7.2 and Sequoia 15.2, and all looks good.

**Comment by gbanasiak** [comment]
For the record, without this fix Thespian was failing a number of `multiprocTCPBase` tests on MacOS with `is not a valid ActorSystem admin` symptom. With the fix, it still fails the following single test, but that's unrelated, and has a simple explanation. I'll report separately.

```
% py.test
[..]
FAILED thespian/test/test_bigmessages.py::TestFuncSimpleActorOperations::testSimpleActorAsk50K[multiprocUDPBase] - AssertionError: assert None == (('hello' * 10) * 1024)
=== [..] 1 failed, 2464 passed, 254 skipped, 3 xfailed, 2518 warnings in 2185.49s (0:36:25) [..] ===
```
